language: ruby

rvm:
  - 2.1

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - bundle exec jekyll build

env:
  global:
  - secure: Kf9QU8q4jKNhGqm5aDHnqACJ8sZ+NK7sz6VYyMS5EZ2gJz/zXmm6JtN7l2zskNal448mNwHAQSURl2TpDHJNLDk+qUwLvwEZP6CVkPy0SaPoUM1FR1VchocEVHM3sBMeGB/5HOXmqh1f1EBSe8hctrgqaCXX715VEAMbYiDoFH/A3ibf89udpnpNH1qXleXNyBXjr56An80Csr9gIPIE2UYb08skNvRZGzxQuCH1VHWLE6+VB31WVos/VOucrlYHEyW6cfEq41BX5akYb+9nr0neCOmX1Nw+YPx2aoyhuTLC1dABs5xe9wjBF16b4ruVQqIWoUE7qHo5Ao0eeuqS3XTz64gKgZB5w7Yt4NuMI8d+ACzdLjbjnq1+qJRGJvyNjClgsy4oBweGfyVXfaQzbx2v0t7Tngrdi5TgOhZr3F46tNyWvh2fRqcMZU+JTtTYmF8de9Rsc0dAx4py/RWY+tWA7beubdC937ZAg0au2dYtDiaFIRnLCknnoxM9sQRK96rnE7mH10yakHiLtB8dqtC+0Vg+MM8p7Qrcp6brWOwtwDKF6wm2y3NLisi/XArsBW8vHkAk0vjczX2hnQZeos0iHOu2Mo4yqbEkkS3XILAhdJy2+H7mIjEj2EZZ4xp2K8xPdTxkrXSzUHYoSIoYpDDLpV/V8S9V44f1xPzJS3w=
  - secure: oUSucRBACk4NnBEdixT9cC5tVO5oK1eks9y18QIwIXWUhddHFYMOOTc6rXmtEIG9qHYZE36k6jLcvHEyU/W1HAuApQdbmQ+nZtN6atKmee07aa2EVheMe7hYKiuhLGNtEIAHgnLqbpO98mBNiWbOaRvv2gnzb0ENO1pXV5Wah6kmfAm9SSnFLa/pFJMOJk+nX0Uhb6oOwiQkfqEJpwoXwmr/rpTClsMYGO56hZRTiD3ErS20SqLdnF8SG6ISBa8QS8KQ338cm2VomfVHviRipzcn8BGyx3zc/NHQSnhe0drnzzbqNkfOdR3exgO3pBDOS8VXt/G/XnmSTiyV9+72kyUz3/PhTLKx9XHPl/8RLDAjkZHDXHbLR9Lib3V4SNN7VKq3Q0Rxhw7nkfTFWE6N5If8vCQsuHesNPTPVtOxA9WFblb4B9t4yRwVlaYKMSsfTaUy8trD9Im6/ImPvY2Ow/Kx0npwn5cnJIW1Lc40OGMHhdxqXRTWQzWGDvrjBYe0I/b+GpOWIbfu4b5iHsWxwYdYNrphnLY7GXmmwUp57ooDMMdHcJZ1eXvo6LTYb4FgGcGymazlNJeOPEY9ZW6K5fhDgQtCC6//ouKnuhbYCgd8xft9xjQsCS2v6g9SxSj8k1AmDWUXi34aPHi5UzrAWAslKkR0rSOBUSaoJWJfOlc=
  - secure: CXC6j+dm2X8SBs6L0XvNcZ3p4f092Y2cRPffikFbKsh2OSVGxyRWWw/ctTi75j+tbXuHPVNqvFBptqHKNZnOz/LCgkqLc+30uwhh/pBfPQxCuYEqYFIM22gGOIteRLwd0JVkbdzoGKRwHMLvQPXCbeXX/gfxBZS+v7Rd3QqqUvijdZhqcd18L2+HPLP28PhJIs4u/6I+bgqQx+4iq7y16uBb2M36BwsEvOH9Pen4Rz432x8StDhz5nGZejXmws6NjpgQQ+1DKZyQ7uGOA/W7uZCixHxW8u2e2Otlun/dJVaL30HJYW7xe5TRDysDrYTtck81P5CAGLM/ivWg1MFrZhd7h5/qRI+gpDPDAIdmFdDudyIDW/KC+WoDihoyh4Ulo0lfTu2dNRQWauZOwaviyIoMQUaLPgECaAqp84dUsZpKzNPKe/UtV7cY0hzGU0pllLGVQBVMq80yOlESGAGny7xJQj+1uHJm5i/ZjToVaKDUA9rVGfotmSCoKKkYZR48zHVNyg4t4d80JoXQyBiw3JZmyPHKKBIqCQBgfpF3PA7omxpwh9DiIYWrPTff/OAry7dcxDfP1EgPR3JarFZYGQZU8mYg0anBSQeEOgPecX82R/+fI4X4A3cqRUxFKi1j7Ayb8DhtKC8rP0p0r0W38x4b8k2Pg3r83boXP9Chy9c=

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: website-crawlera-com
  skip_cleanup: true
  local_dir: _site
  acl: public_read
  on:
    branch: master

after_deploy:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $DISTID --paths '/*'
