language: ruby

rvm:
  - 2.1

script:
  - bundle exec jekyll build

env:
  global:
    secure: Kf9QU8q4jKNhGqm5aDHnqACJ8sZ+NK7sz6VYyMS5EZ2gJz/zXmm6JtN7l2zskNal448mNwHAQSURl2TpDHJNLDk+qUwLvwEZP6CVkPy0SaPoUM1FR1VchocEVHM3sBMeGB/5HOXmqh1f1EBSe8hctrgqaCXX715VEAMbYiDoFH/A3ibf89udpnpNH1qXleXNyBXjr56An80Csr9gIPIE2UYb08skNvRZGzxQuCH1VHWLE6+VB31WVos/VOucrlYHEyW6cfEq41BX5akYb+9nr0neCOmX1Nw+YPx2aoyhuTLC1dABs5xe9wjBF16b4ruVQqIWoUE7qHo5Ao0eeuqS3XTz64gKgZB5w7Yt4NuMI8d+ACzdLjbjnq1+qJRGJvyNjClgsy4oBweGfyVXfaQzbx2v0t7Tngrdi5TgOhZr3F46tNyWvh2fRqcMZU+JTtTYmF8de9Rsc0dAx4py/RWY+tWA7beubdC937ZAg0au2dYtDiaFIRnLCknnoxM9sQRK96rnE7mH10yakHiLtB8dqtC+0Vg+MM8p7Qrcp6brWOwtwDKF6wm2y3NLisi/XArsBW8vHkAk0vjczX2hnQZeos0iHOu2Mo4yqbEkkS3XILAhdJy2+H7mIjEj2EZZ4xp2K8xPdTxkrXSzUHYoSIoYpDDLpV/V8S9V44f1xPzJS3w=

deploy:
  provider: s3
  access_key_id:
    secure: QaAdrz+Mp9PuIxtxv0tT/zBewkpuyBysCKdsksAL5gF6MZ1VVZGhzuvZ9CwO8w7cIPPbOQw0/0p1/mZiCXH9C7JbsMGCB2h38vmVX556eMd25od8XIYYfe7JwE5GXYVG3x5DPD/+rh83ezI2wtC3wOtRDp2KoIJ01koVdvhWlBQmIYputfvKKIaKezp4kGPrI91sY+V7O7vK7s3SlkSmD8J6FoF8uegOn+bAy21rWnz1sJGVeLaSTjSJ39W6fKqC1D5hS4cUSxwl2ubKEH25l+CxWicDk6bryx8kXl0btO36v35gwqZmO1zyLZVYmaY39GcF1eTNZBpjCtAcvqwpQ3ZUKlbzS8iu8sHaruAYO2sVMSgKu/hhpwpJY5HbhlFem6eSsT41biAUC/Q5+jimbz9fwrDXS86ls6D6cOz9NsahxO4jOeY+xr7v/ZkLfGSKQMqyWenzq5uiRJKBD9BpUBx5YuI5bssAwfcYPR3owamfVtnW1DwhJhQVBnDtZLF3ShIbZRIFgDv+tEfHjgWUjOT+ICD7rawY8T5LtY60GIVzIirVY+TDol+JiB8ycYyPXCQpDyKaWS2pw2QcqKI0HV485Jvoota+wenR7vc6I+UL9KAKfXFR2jS1o5E7bOk3U3Gg984N2NvesPvzvCdrT/lBUYJFWyPHlEpn7g9kU+M=
  secret_access_key:
    secure: i3xzo5ZG9cHugtF7uWenJ/cu0sSVlVMhk+A6neCoqs/LGWEnJWXLKZpsj+WMzAvZ2pbjsWRG54JxfAmYdFJlb6Z7cxF40Awz1NxQutO2lAwKRHOKNqicFSUaOYeNOsdpSOHqp4rqqK6ivRQyL+kJm7W1wi9FJSo7dwwPLTUtITZoDcRYjvszOleR6Mx2y7a58cxipfSwtJPKjk1GYb/N+3pM8vSocB3BdO+AKTso7vzU426kKPVz1i31H08Fq9+JOvLpimdz+dbVyq7GepLo47APlIEvo7MPP81C6yVhJb+bu/EkaEPcy9VUQ0lwQL8BDB2adQu6kj5nA/GgDd9052Xqw82CFuJjzrSSeaJ5ofbLuUDDHCc6TBA7ryZKP5BDRmEkeYG/Qgy7gmQ/czQ8ZosH79PnphYbBYsovceyprB5BI90fu3dm4LX30VY5n3puQHebd3H6XWA40+3cwZIHuES9ukMxANSfC83iCzGk0QQ7GhDVIU/Al0twIcInLeXhv2keMb9j+mtL9GEpsKQcabNPPMiAPqQx79jp8ZGL1HtBhBhFFsFjrFahnqVXxTNcrJQu6c7Tjcb92EdSZQgsROXZd9g1aqpCFrXEo181alWRGFq0wJmRJxAjGJq/mHyJwlaDwyyqwv80l5DYdu1KFqzMimKaeZL8ShWYwzThUI=
  bucket: website-crawlera-com
  skip_cleanup: true
  local_dir: _site
  acl: public_read
  on:
    branch: master

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $DISTID --paths '/*'
